AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'contact-us-sam-app

  '
Globals:
  Function:
    Timeout: 10
  Api:
    Cors:
      AllowOrigin: '''*'''
      AllowHeaders: '''Content-Type,X-WARM-UP,X-Amz-Date,Authorization,X-Api-Key'''
Resources:
  ContactUsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://contact-us-sam-app/b5cea3dea6aec39e3925a003b84fe90d
      Handler: com.gralll.sam.App::handleRequest
      Runtime: java8
      MemorySize: 256
      AutoPublishAlias: live
      DeploymentPreference:
        Type: Canary10Percent10Minutes
      Policies:
      - AWSLambdaExecute
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - ses:SendEmail
          - ses:SendRawEmail
          Resource: arn:aws:ses:eu-west-1:548476639829:identity/aleksandrgruzdev11@gmail.com
        - Effect: Allow
          Action:
          - dynamodb:List*
          Resource: '*'
        - Effect: Allow
          Action:
          - dynamodb:Get*
          - dynamodb:PutItem
          - dynamodb:DescribeTable
          Resource: arn:aws:dynamodb:*:*:table/ContactUsTable
      Events:
        ContactUs:
          Type: Api
          Properties:
            Path: /contact
            Method: post
  ContactUsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: Id
        Type: String
      TableName: ContactUsTable
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
Outputs:
  ContactUsApi:
    Description: API Gateway endpoint URL for Prod stage for ContactUs function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/contact/
  ContactUsFunction:
    Description: ContactUs Lambda Function ARN
    Value:
      Fn::GetAtt:
      - ContactUsFunction
      - Arn
  ContactUsFunctionIamRole:
    Description: Implicit IAM Role created for ContactUs function
    Value:
      Fn::GetAtt:
      - ContactUsFunctionRole
      - Arn
